### ISSUE TITLE
Plugin Error: PermissionsDispatcher plugin threw an uncaught NullPointerException. Disable Plugin 12:38:45 NullPointerException: null

### ISSUE THREAD

**Issue by ArthurSav** [permissions-dispatcher/permissions-dispatcher-plugin#18]
Using the latest Android Studio 2.1.1

`
Plugin Error: PermissionsDispatcher plugin threw an uncaught NullPointerException. Disable Plugin 12:38:45 NullPointerException: null
`

**Comment by shiraji** [comment]
Do you install Kotlin plugin?

**Comment by shiraji** [comment]
Could you give me the steps reproducing this issue?

**Comment by alexwan02** [comment]
### I have the same issue

PermissionsDispatcher Library is necessary  or not ?
![image](https://cloud.githubusercontent.com/assets/8053520/15321035/a1f9fdba-1c66-11e6-8407-f98d8a742a7b.png)
![image](https://cloud.githubusercontent.com/assets/8053520/15321057/b6df8b64-1c66-11e6-9641-c28bfc2f5811.png)

Android Studio Info : 
![image](https://cloud.githubusercontent.com/assets/8053520/15321082/e01be554-1c66-11e6-9315-34e8a6033be9.png)

**Comment by shiraji** [comment]
ok, how to get this error? could you give me steps? @alexwan1989

**Comment by alexwan02** [comment]
@shiraji PermissionsDispatcher Library is necessary or not ? 
I use the plugin without PermissionsDispatcher Library 。

**Comment by shiraji** [comment]
It is necessary. I will add feature that add dependancies in future version. 

For now, please check https://github.com/hotchemi/PermissionsDispatcher#download

**Comment by alexwan02** [comment]
@shiraji  thanks , careless for the doc

> IntelliJ plugin for supporting PermissionsDispatcher. This is NOT official plugin.

**Comment by shiraji** [comment]
Hi, @ArthurSav do you have the same problem?

**Comment by shiraji** [comment]
@alexwan1989 Thank you for your response! I will document for this.

**Comment by ArthurSav** [comment]
Yes, i didn't have the `PermissionsDispatcher` library.
A mention in the installation guide about it would possibly help to avoid this issue in the future.
