### ISSUE TITLE
PD v2.2.0

### ISSUE THREAD

**Issue by shiraji** [permissions-dispatcher/permissions-dispatcher-plugin#26]
PermissionsDispatcher  v2.2.0 is available https://github.com/hotchemi/PermissionsDispatcher/releases/tag/2.2.0

~~I don't think there is no change for this plugin but make sure it is working.~~

I lie. This plugin need to support `maxSdkVersion`. Maybe add checkbox and then if the checkbox is selected, add `maxSdkVersion = 18` from manifest file. (or just show text box for maxSdkVersion value)
- [x] Support maxSdkVersion
- [x] Update README

**Comment by hotchemi** [comment]
Awesome!!!!!
