### ISSUE TITLE
can't install this plugin

### ISSUE THREAD

**Issue by gqandroid** [permissions-dispatcher/permissions-dispatcher-plugin#35]
android studio 2.2.2
when i install this plugin from browse repositories, it can't download. 
so i use install plugin from disk, this can install but when i restart android studio, it warn this plugin has some problems.
please help me!

**Comment by shiraji** [comment]
Does your Android Studio install Kotlin plugin? (It should be bundled...)

**Comment by gqandroid** [comment]
Thanks! It works.

**Comment by shiraji** [comment]
Your welcome. Thanks for installing this plugin!
