### ISSUE TITLE
Add settings for PM latest version

### ISSUE THREAD

**Issue by shiraji** [permissions-dispatcher/permissions-dispatcher-plugin#39]
At this moment, [PdVersion](https://github.com/shiraji/permissions-dispatcher-plugin/blob/master/src/main/kotlin/com/github/shiraji/permissionsdispatcherplugin/data/PdVersion.kt#L16) manages latest version of PM. I want add settings to edit "latest version".

**Comment by shiraji** [comment]
seems not reasonable...i may close this issue...

**Comment by hotchemi** [comment]
Okay!!!

**Comment by shiraji** [comment]
Thanks!!!
