### ISSUE TITLE
It doesn't work 

### ISSUE THREAD

**Issue by BigKarel** [permissions-dispatcher/permissions-dispatcher-plugin#43]
gradle:
--------
dependencies {
    //permissions
    compile appDependencies.permissionsDispatcher
    annotationProcessor appDependencies.permissionsDispatcherProcessor
}
----------
appDependencies = [
            permissionsDispatcher  : "com.github.hotchemi:permissionsdispatcher:${permissionsDispatcherVersion}",
            permissionsDispatcherProcessor: "com.github.hotchemi:permissionsdispatcher-processor:${permissionsDispatcherVersion}",
    ]
-----------
It doesn't work ,,fragment or activity generate show : 
![image](https://cloud.githubusercontent.com/assets/8768949/25270969/09950ef2-26b5-11e7-95cc-f39687b8102e.png)

**Comment by shiraji** [comment]
wow. I didin't know that syntax. Let's me rethink this feature.
