### ISSUE TITLE
No annotation processing settings found.

### ISSUE THREAD

**Issue by RunningShadow-007** [permissions-dispatcher/permissions-dispatcher-plugin#81]
[PermissionsManager Plugin] Missing settings: No annotation processing settings found. Use 'android gradle plugin version >= 2.2' or 'android-apt'

**Comment by RunningShadow-007** [comment]
![qq20171121-144432-hd](https://user-images.githubusercontent.com/10829703/33058535-03205acc-cecb-11e7-87e1-cee29486b12d.gif)

I can't generate the dependency in the app.gradle  
then I got the warning on the upper floor

**Comment by shiraji** [comment]
Which version of android gradle plugin do you use?

**Comment by shiraji** [comment]
Because of lack of response, I will close this issue. Feel free to reopen this if you find more info.
