### ISSUE TITLE
No plugins found for query PermissionsDispatcher

### ISSUE THREAD

**Issue by jp1017** [permissions-dispatcher/permissions-dispatcher-plugin#9]
![22](https://cloud.githubusercontent.com/assets/7868514/15150127/8f89257e-16fe-11e6-9516-b5a4d218accd.jpg)

![11](https://cloud.githubusercontent.com/assets/7868514/15150133/94ad6100-16fe-11e6-9e1c-03f7079f6e42.jpg)

So, How to get this fantastic plugin?

**Comment by shiraji** [comment]
Well...I haven't release this plugin, yet. I will let you know when it's ready! Thanks.

**Comment by shiraji** [comment]
Uploaded it. https://plugins.jetbrains.com/plugin/8349 is plugin page. Let's see JetBrains accepts this plugin.

**Comment by shiraji** [comment]
Now, it is on the list. Could you try that?

**Comment by jp1017** [comment]
Well done, I got it.
Thanks very very much.
:smile:

**Comment by shiraji** [comment]
NP! Thank yor for reporting issue
