### ISSUE TITLE
androidannotations  not used Permissions-dispatcher

### ISSUE THREAD

**Issue by xiangou** [permissions-dispatcher/permissions-dispatcher-plugin#91]
my project  is used  androidannotations      https://github.com/androidannotations/androidannotations
and cannot  Integrate  permissions-dispatcher

java.lang.RuntimeException: permissions.dispatcher.processor.exception.NoAnnotatedMethodsException: Annotated class 'LoginActivity_' doesn't have any method annotated with '@NeedsPermission'

**Comment by hotchemi** [comment]
@xiangou have you checked https://github.com/permissions-dispatcher/AndroidAnnotationsPermissionsDispatcherPlugin ?

**Comment by xiangou** [comment]
ok thanks
