### ISSUE TITLE
work in Activity,doesn't work in Fragment???

### ISSUE THREAD

**Issue by lydlovezjr** [permissions-dispatcher/permissions-dispatcher-plugin#93]
<img width="546" alt="微信截图_20190806140004" src="https://user-images.githubusercontent.com/19246347/62514790-e298bb00-b852-11e9-8017-a78d8f74d4a3.png">
<img width="770" alt="微信截图_20190806140048" src="https://user-images.githubusercontent.com/19246347/62514791-e3c9e800-b852-11e9-95a1-6324e47dca83.png">

**Comment by lydlovezjr** [comment]
Android Studio Version is 3.4.2 And plugin Version  is 3.1.0.

**Comment by zrq1060** [comment]
I have the same problem.How did you do it?
